# Generated by Django 4.2.4 on 2023-09-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='totken_type',
            new_name='token_type',
        ),
        migrations.AlterField(
            model_name='spotifytoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
